name: Run Request

on:
  push:
    branches: ["*"]
  schedule:
    - cron: "*/30 * * * *"

jobs:
  Send:
    name: Request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - run: npm install
      - run: npm start
        timeout-minutes: 20
